spring:
  application:
    name: fzq-config-service
  cloud:
    config:
      server:
        git:
          uri: http://172.23.216.151/fzq/fzqConfigService.git
          username: fzq
          password: fanzhiqiang.02
          basedir: /home/fzq/config/
eureka:
  instance:
    hostname: fzq-config-service
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
server:
  port: 8888
